### ISSUE TITLE
Build failure with latest Angular

### ISSUE THREAD

**Issue by mgechev** [Gbuomprisco/ng2-material-dropdown#66]
Because of the type definitions in `ng2-menu-item.d.ts` and the removal of the deprecated `Renderer`, `ng2-material-dropdown` no longer works with the latest `@angular/core`.

You can find the failure in the CI [here](https://circleci.com/gh/mgechev/ngcc-validation/101).

In the official version 9 release, we'll no longer have `Renderer` part of Angular.

**Comment by Gbuomprisco** [comment]
Hi @mgechev, I release v0.11.0, it should fix that

**Comment by IvanWSM** [comment]
Hi! This is still not working for me with version `0.11.0` from `ngx-chips` dependency, any solution?

![image](https://user-images.githubusercontent.com/52294856/68717467-7e317a00-056c-11ea-8235-62f03aeb7854.png)

**Comment by Gbuomprisco** [comment]
This may be due to a package version (angular-devkit/build-angular):
• this is the version I use to build on v9: "@angular-devkit/build-angular": "^0.803.19"
• this is the version I use to build on v8": "@angular-devkit/build-angular": "^0.803.8"
